name: Main
on:
  - push
  - cron: '22 0,12 * * *'
jobs:
  download-and-handle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: curl https://data.mpsv.cz/od/soubory/volna-mista/volna-mista.json --output volna-mista.json
      - run: npm start
