name: Fetch
on: [push]
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - run: date
      - run: curl https://data.mpsv.cz/od/soubory/volna-mista/volna-mista.json --output data.json
      - run: ls
      - run: date
